# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: 2024 Tobias Hienzsch

[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "pffdtd"
version = "0.1.0"
description = "Pretty Fast FDTD"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE.txt"]
authors = [{ name = "Tobias Hienzsch", email = "post@tobias-hienzsch.de" }]
requires-python = ">=3.11"
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

dependencies = [
    "click",
    "h5py",
    "matplotlib",
    "memory_profiler",
    "numba",
    "numpy",
    "opencv-python",
    "pandas",
    "plotly",
    "polyscope",
    "psutil",
    "resampy",
    "scipy",
    "sympy",
    "tqdm",
    "tabulate",
    "xlrd",
]

[project.urls]
Homepage = "https://github.com/tobanteAudio/pffdtd"
Issues = "https://github.com/tobanteAudio/pffdtd/issues"

[project.optional-dependencies]
gui = ["PySide6"]
test = ["pytest", "pytest-cov"]
dev = ["autopep8", "conan", "mypy", "pre-commit", "pylint"]
types = ["pandas-stubs", "scipy-stubs", "types-psutil"]

# mayavi/vtk fails to build on Windows. Mostly not needed anyway. Use polyscope instead.
visualize = ["mayavi", "vtk"]

[project.scripts]
pffdtd = "pffdtd.cli:main"
pffdtd-gui = "pffdtd.gui.main:main"

[tool.setuptools.packages.find]
where = ["src/python"]

[tool.pytest.ini_options]
minversion = "7.0"
addopts = [
    "-ra",
    "--strict-markers",
    "--strict-config",
    "--durations=10",
    "--durations-min=1.0",
]
xfail_strict = true
filterwarnings = ["error"]
testpaths = ["src/python/test/*"]
markers = ["slow: marks tests as slow (deselect with '-m \"not slow\"')"]

[tool.autopep8]
max_line_length = 200
ignore = []
in-place = true
recursive = true
aggressive = 0

[tool.mypy]
packages = "pffdtd"
python_version = "3.11"
warn_redundant_casts = true
# warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = true
exclude = []
disable_error_code = ["override", "overload-overlap"]

[[tool.mypy.overrides]]
module = ["h5py", "mayavi", "numba", "polyscope", "resampy", "tqdm", "tvtk.*"]
ignore_missing_imports = true
